version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./www:/var/www
    environment:
      - ACME_AGREE=true
  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - authentication_db
  authentication_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USR}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./authentication/create_db.sql:/docker-entrypoint-initdb.d/db_event.sql
  mq_consumer:
    build:
      context: ./mq_consumer
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3000:3000"
  writer:
    build:
      context: ./writer
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8082:8080"
    depends_on:
      - writer_db
  writer_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USR}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - ./writer/create_db.sql:/docker-entrypoint-initdb.d/db_event.sql


